# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: 'pork'
        if: secrets.FRONT_DOOR_PASSWORD == true
        run: echo 'It true'
        
      - name: 'pork 2'
        if: secrets.FRONT_DOOR_PASSWORD == false
        run: echo 'It false'

      - name: 'naski' 
        uses: gliech/create-github-secret-action@v1
        with:
          name: FRONT_DOOR_PASSWORD
          value: true
          pa_token: ${{ secrets.PA_TOKEN }}
          
      - name: 'Test'
        run: echo 'It works'
            
      
